MindLabConnect/Controllers/AccountController.cs
using System.Web.Mvc;

namespace MindLabConnect.Controllers
{
    public class AccountController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MindLabConnect/Controllers/DocumentationController.cs
using System.Web.Mvc;

namespace MindLabConnect.Controllers
{
    public class DocumentationController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MindLabConnect/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MindLabConnect.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MindLabConnect/Controllers/LandingController.cs
using System.Web.Mvc;

namespace MindLabConnect.Controllers
{
    public class LandingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MindLabConnect/Controllers/MarketingController.cs
using System.Web.Mvc;

namespace MindLabConnect.Controllers
{
    public class MarketingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MindLabConnect/Controllers/ProductController.cs
using System.Web.Mvc;

namespace MindLabConnect.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MindLabConnect/Views/Documentation/Index.cshtml
@{
    ViewBag.Title = "Documentation";
    Layout = "~/Views/Shared/_DocumentationLayout.cshtml";
}

<div class="navbar navbar-fixed-top ml-navbar">
    <div class="container-fluid ml-container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">
                <img src="@Url.Content("~/Content/images/logo@2x.png")" width="217" />
            </a>
        </div>
    </div>
</div>

<div class="container-fluid ml-container-fluid">
    <h1>MindLab Connect Page Templates</h1>
    <ul class="list-unstyled">
        <li><h3><a href="@Url.Action("Index", "Home")">1_Home</a></h3></li>
        <li><h3><a href="@Url.Action("Index", "Landing")">2_Landing</a></h3></li>
        <li><h3><a href="@Url.Action("Index", "Product")">3_Product</a></h3></li>
        <li><h3><a href="@Url.Action("Index", "Marketing")">4_Marketing</a></h3></li>
        <li><h3><a href="@Url.Action("Index", "Account")">5_Account</a></h3></li>
    </ul>
    <br />
    <h1>Getting Started</h1>
    <ul class="list-unstyled">
        <li><h3><a href="#" data-toggle="modal" data-target="#assetsModal">1_Front-End Assets</a></h3></li>
        <li><h3><a href="#" data-toggle="modal" data-target="#sassModal">2_SASS Documentation</a></h3></li>
        <li><h3><a href="#" data-toggle="modal" data-target="#refModal">3_References</a></h3></li>
    </ul>
    <br />
    <h1>Questions?</h1>
    <ul class="list-unstyled">
        <li><h3><a href="mailto:dylanjmcdonald@gmail.com"><i class="fa fa-envelope"></i> Email</a></h3></li>
        <li><h3><a href="https://twitter.com/dylanjmcdonald" target="_blank"><i class="fa fa-twitter"></i> Connect on Twitter</a></h3></li>
        <li><h3><a href="https://www.linkedin.com/profile/view?id=23932035" target="_blank"><i class="fa fa-linkedin"></i> Connect on LinkedIn</a></h3></li>
    </ul>
</div>

@*FRONT-END ASSETS MODAL*@
<div class="modal fade" id="assetsModal" tabindex="-1" role="dialog" aria-labelledby="assetsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="assetsModalLabel">Front-End Assets</h4>
            </div>
            <div class="modal-body">
                <ul class="list-unstyled">
                    <li><h5>CSS</h5></li>
                    <li><span class="label label-default">Vendor</span> /Content/css/*</li>
                    <li><span class="label label-default">Vendor</span> /Content/fonts/mpix234/stylesheet.css</li>
                    <li><h5>Fonts</h5></li>
                    <li><span class="label label-default">Vendor</span> /Content/fonts/*</li>
                    <li><h5>Images</h5></li>
                    <li><span class="label label-primary">Custom</span> /Content/images/*</li>
                    <li><h5>Javascript</h5></li>
                    <li><span class="label label-default">Vendor</span> /Scripts/jquery-2.1.3.js</li>
                    <li><span class="label label-default">Vendor</span> /Scripts/modernizr-2.6.2.js</li>
                    <li><span class="label label-default">Vendor</span> /Scripts/bootstrap.js</li>
                    <li><span class="label label-default">Vendor</span> /Scripts/respond.js</li>
                    <li><span class="label label-default">Vendor</span> /Scripts/classie.js</li>
                    <li><span class="label label-default">Vendor</span> /Scripts/dialogFx.js</li>
                    <li><span class="label label-primary">Custom</span> /Scripts/main.js</li>
                    <li><h5>SASS</h5></li>
                    <li><span class="label label-warning">Mixture</span> /Content/sass/*</li>
                    <li><h5>Notes</h5></li>
                    <li>All vendor files have not been modified from original source.</li>
                    <li>Feel free to use minified versions or minify through Kentico.</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@*SASS MODAL*@
<div class="modal fade" id="sassModal" tabindex="-1" role="dialog" aria-labelledby="sassModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="sassModalLabel">SASS Documentation</h4>
            </div>
            <div class="modal-body">
                <ul class="list-unstyled">
                    <li><h5>Files</h5></li>
                    <li><span class="label label-default">Vendor</span> /Content/sass/bootstrap/*</li>
                    <li><span class="label label-primary">Custom</span> /Content/sass/components/*</li>
                    <li><span class="label label-primary">Custom</span> /Content/sass/layout/*</li>
                    <li><span class="label label-primary">Custom</span> /Content/sass/pages/*</li>
                    <li><span class="label label-primary">Custom</span> /Content/sass/_base.scss</li>
                    <li><span class="label label-default">Vendor</span> /Content/sass/_bootstrap-compass.scss</li>
                    <li><span class="label label-default">Vendor</span> /Content/sass/_bootstrap-mincer.scss</li>
                    <li><span class="label label-default">Vendor</span> /Content/sass/_bootstrap-sprockets.scss</li>
                    <li><span class="label label-default">Vendor</span> /Content/sass/_bootstrap.scss</li>
                    <li><span class="label label-primary">Custom</span> /Content/sass/_variables.scss</li>
                    <li><span class="label label-primary">Custom</span> /Content/sass/styles.scss</li>
                    <li><h5>Questions</h5></li>
                    <li>
                        <p>
                            <b>Q: Where are my CSS files to use on the site?</b>
                            <br /><b>A:</b> All generated files are not included
                            into the repository. In order to generate the CSS files
                            that you will use for the site, simply use the following
                            command from the sites root directory:<br /><br />
                            <code>sass --watch MindLabConnect/Content/sass:MindLabConnect/Content/css</code>
                            <br /><br />The CSS files will then be generated and 
                            available in the /Content/css directory.
                        </p>
                    </li>
                    <li>
                        <p>
                            <b>Q: I need to customize a bootstrap component. How do I do that?</b>
                            <br /><b>A:</b> Copy the bootstrap .scss file into the components
                            sass directory and only include/overwrite necessary modifications.
                            Include the new .scss component file in the /Content/sass/styles.scss
                            file.
                        </p>
                    </li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@*REFERENCES MODAL*@
<div class="modal fade" id="refModal" tabindex="-1" role="dialog" aria-labelledby="refModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="refModalLabel">References</h4>
            </div>
            <div class="modal-body">
                <ul class="list-unstyled">
                    <li><a href="http://getbootstrap.com/" target="_blank">Bootstrap</a></li>
                    <li><a href="http://jquery.com/" target="_blank">jQuery</a></li>
                    <li><a href="https://github.com/scottjehl/Respond" target="_blank">Respond</a></li>
                    <li><a href="http://sass-lang.com/" target="_blank">SASS</a></li>
                    <li><a href="https://rubygems.org/gems/sass" target="_blank">SASS Gem</a> <i class="text-muted">(Requires Ruby)</i></li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

MindLabConnect/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.PageTitle = "Hello Lauren - <span>how can we build better workplaces together?</span>";
}

<div class="container-fluid ml-container-fluid">
    <div class="row">
        <div class="col-md-6">

            <div>
                <h2>Getting Started</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet molotribus.</p>
                    </div>
                </div>
                <small><b>Your Progress:</b></small>
                <div class="progress">
                    <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                        <span>50% Complete</span>
                    </div>
                </div>
                <p><a href="#"><i class="mpi">&#218;</i> Start Your Next Step</a></p>
            </div>

            <div>
                <h2>Certification</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet molotribus.</p>
                        <p><a href="#"><i class="mpi">&#218;</i> Learn More</a></p>
                    </div>
                </div>
            </div>

            <div>
                <h2>LinkedIn Discussions</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                    </div>
                    <div class="media-body">
                        <span><a href="#">Does anyone have any suggestions for DiSC profile reveals in a group setting?</a></span>
                        <p>Lorem ipsum set dolor amet lorem ipsum set dolor amet lorem...</p>
                        <p><small class="text-info">POSTED 1 DAY AGO</small></p>
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                    </div>
                    <div class="media-body">
                        <span><a href="#">What works for me: promoting Everything DiSC behavior assessments to IT teams.</a></span>
                        <p>Lorem ipsum set dolor amet lorem ipsum set dolor amet lorem. Mus minusan debiti re porrorem reiusam rae erem sa, autem...</p>
                        <p><small class="text-info">POSTED 3 DAYS AGO</small></p>
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                    </div>
                    <div class="media-body">
                        <span><a href="#">Why a Train-the-Trainer approach makes sense.</a></span>
                        <p>Lorem ipsum set dolor amet lorem ipsum set dolor amet lorem...</p>
                        <p><small class="text-info">POSTED 4 DAYS AGO</small></p>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div>
                <h2>Brands</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <h5 class="media-heading">Everything DiSC<sup>&reg;</sup> Work of Leaders Profile</h5>
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> More Information</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Purchase New Materials</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Customize Documents</a></li>
                        </ul>
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <h5 class="media-heading">The Five Behaviors of a Cohesive Team<sup>&reg;</sup></h5>
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> More Information</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Purchase New Materials</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Customize Documents</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div>
                <h2>Beta Testing</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <h5 class="media-heading">[Product Name]</h5>
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> More Information</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

MindLabConnect/Views/Landing/Index.cshtml
@{
    ViewBag.Title = "Landing Page";
    ViewBag.PageTitle = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid ml-container-fluid">
    <div class="row">
        <div class="col-md-6">

            <div>
                <h2>Work of Leaders</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> Reorder Tests</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Personalize Documents</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div>
                <h2>Work of Leaders</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> Reorder Tests</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Personalize Documents</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div>
                <h2>Work of Leaders</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> Reorder Tests</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Personalize Documents</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div>
                <h2>363 for Leaders</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> Reorder Tests</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Personalize Documents</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div>
                <h2>363 for Leaders</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> Reorder Tests</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Personalize Documents</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div>
                <h2>Five Behaviors of a Cohesive Team</h2>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="http://placehold.it/50x50" alt="...">
                    </div>
                    <div class="media-body">
                        <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                        <ul class="list-unstyled">
                            <li><a href="#"><i class="mpi">&#218;</i> Reorder Tests</a></li>
                            <li><a href="#"><i class="mpi">&#218;</i> Personalize Documents</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

MindLabConnect/Views/Marketing/Index.cshtml
@{
    ViewBag.Title = "Marketing Page";
    ViewBag.PageTitle = "Marketing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid ml-container-fluid">
    <div class="row">
        <div class="col-md-12">
            <ul class="list-unstyled list-inline breadcrumb-container">
                <li>Filter by</li>
                <li>
                    <ol class="breadcrumb">
                        <li><a href="#">Products</a></li>
                        <li><a href="#">Case Studies</a></li>
                        <li><a href="#">Sample Reports</a></li>
                        <li><a href="#">Logos &amp; Images</a></li>
                    </ol>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Subhead</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a data-toggle="modal" data-target="#video-modal" href="#"><img src="http://placehold.it/440x250" alt="" /></a>
            <br />
            <br />
            <p><b>Video Title</b></p>
            <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
            <ul class="list-unstyled">
                <li><a href="#"><i class="mpi">&#218;</i> Reorder Tests</a></li>
                <li><a href="#"><i class="mpi">&#218;</i> Personalize Documents</a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Upcoming Events</div>
                <div class="panel-body">
                    <div class="media">
                        <div class="media-body">
                            <h5 class="media-heading"><a href="#">Event Name</a></h5>
                            <p>Mus minusan debiti re por rorem reiusam rae erem sa, au tem dolliquides delis sunt ut enimet moloribus.</p>
                            <ul class="list-unstyled">
                                <li><a href="#"><i class="mpi">&#218;</i> Learn More</a></li>
                                <li><a href="#"><i class="mpi">&#218;</i> Register for this event</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="media">
                        <div class="media-body">
                            <h5 class="media-heading"><a href="#">Event Name</a></h5>
                            <p>Mus minusan debiti re por rorem reiusam rae erem sa, au tem dolliquides delis sunt ut enimet moloribus.</p>
                            <ul class="list-unstyled">
                                <li><a href="#"><i class="mpi">&#218;</i> Learn More</a></li>
                                <li><a href="#"><i class="mpi">&#218;</i> Register for this event</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Start "General Tools" -->
    <div class="row">
        <div class="col-md-12">
            <h2>General Tools</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Video Title</a> <small>Video</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Watch Video</a></li>
                    </ul>
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Document Title</a> <small>PDF</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Document Title</a> <small>PDF</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End "General Tools" -->
    <!-- Start "Case Studies" -->
    <div class="row">
        <div class="col-md-12">
            <h2>Case Studies</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Case Study Title</a> <small>PDF</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Presentation Title</a> <small>PPT</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam rae erem sa, autem dolliquides delis sunt ut enimet moloribus.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End "Case Studies" -->
    <!-- Start "Logos & Images" -->
    <div class="row">
        <div class="col-md-12">
            <h2>Logos &amp; Images</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Image 1</a> <small>JPG</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Image 3</a> <small>JPG</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Image 2</a> <small>PNG</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="http://www.gravatar.com/avatar/?s=50&d=mm" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="media-heading"><a href="#">Image 4</a> <small>PNG</small></h5>
                    <p>Mus minusan debiti re porrorem reiusam.</p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="mpi">&#218;</i> Download</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End "Logos & Images" -->
</div>